# Generated by Django 5.1.2 on 2026-06-10 08:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0003_cliente_referidor'),
        ('procesos', '0005_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=False)),
                ('api_url', models.URLField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Proveedor de facturación',
                'verbose_name_plural': 'Proveedores de facturación',
            },
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('NOMINA', 'Nómina'), ('PROVEEDORES', 'Proveedores'), ('SERVICIOS', 'Servicios'), ('GASTOS_ADMIN', 'Gastos administrativos'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('beneficiario', models.CharField(blank=True, default='', max_length=200)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('concepto', models.CharField(max_length=500)),
                ('tipo_servicio', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_emision', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField()),
                ('termino_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('15_DIAS', '15 Días'), ('30_DIAS', '30 Días'), ('45_DIAS', '45 Días'), ('60_DIAS', '60 Días')], default='CONTADO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGO_PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('notas_internas', models.TextField(blank=True, default='')),
                ('cufe', models.CharField(blank=True, default='', max_length=200)),
                ('cuds', models.CharField(blank=True, default='', max_length=200)),
                ('xml_generado', models.TextField(blank=True, default='')),
                ('respuesta_dian', models.TextField(blank=True, default='')),
                ('codigo_qr', models.TextField(blank=True, default='')),
                ('fecha_validacion_dian', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='procesos.casojuridico')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='comercial.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='procesos.proceso')),
                ('proveedor_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.proveedorfacturacion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tesoreria.factura')),
            ],
            options={
                'verbose_name': 'Ítem de factura',
                'verbose_name_plural': 'Ítems de factura',
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREDITO', 'Nota Crédito'), ('DEBITO', 'Nota Débito')], max_length=10)),
                ('motivo', models.CharField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('anulada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tesoreria.factura')),
            ],
            options={
                'verbose_name': 'Nota Crédito/Débito',
                'verbose_name_plural': 'Notas Crédito/Débito',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('PSE', 'PSE'), ('CONSIGNACION', 'Consignación'), ('TARJETA', 'Tarjeta')], default='TRANSFERENCIA', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tesoreria.factura')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
