# Generated by Django 5.1.2 on 2026-06-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente DIAN'), ('EMITIDA', 'Emitida'), ('RECHAZADA', 'Rechazada DIAN'), ('PAGO_PARCIAL', 'Pago Parcial'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20),
        ),
    ]
