# Generated by Django 5.1.2 on 2026-06-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_factus',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
