# Generated by Django 5.1.2 on 2026-06-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_procesointerno_precio'),
        ('tesoreria', '0003_factura_numero_factus'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaitem',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de IVA aplicado (0 = exento)', max_digits=5),
        ),
        migrations.AddField(
            model_name='facturaitem',
            name='iva_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='facturaitem',
            name='proceso_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_factura', to='procesos.procesointerno'),
        ),
    ]
