# Generated by Django 5.1.2 on 2026-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('comision', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('banco', models.CharField(blank=True, default='', max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], default='AHORROS', max_length=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referidor',
                'verbose_name_plural': 'Referidores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
