# Generated by Django 5.1.2 on 2026-06-16 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_cliente_referidor'),
        ('referidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto del pago')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% comisión aplicado')),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Comisión generada')),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='comercial.cliente')),
                ('referidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='referidos.referidor')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
