# Generated by Django 5.1.2 on 2026-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COMERCIAL', 'Comercial'), ('COLABORADOR', 'Colaborador'), ('ABOGADO', 'Abogado')], default='COLABORADOR', max_length=20),
        ),
    ]
