# Generated by Django 5.1.2 on 2026-06-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_cliente_tipo_cliente_barrio_and_more'),
        ('referidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='referidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_referidos', to='referidos.referidor'),
        ),
    ]
