# Generated by Django 5.1.2 on 2026-06-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_cliente_referidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteNegativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200, verbose_name='Entidad / Obligación')),
                ('numero_obligacion', models.CharField(blank=True, max_length=100, verbose_name='No. Obligación')),
                ('estado_central', models.CharField(blank=True, max_length=100, verbose_name='Estado Central')),
                ('gestion', models.CharField(default='PENDIENTE', max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('permiso_negativa_hasta', models.DateField(blank=True, null=True, verbose_name='Perm. Negativa hasta')),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_negativos', to='comercial.cliente')),
            ],
            options={
                'verbose_name': 'Reporte Negativo',
                'verbose_name_plural': 'Reportes Negativos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
