# Generated by Django 5.1.2 on 2026-06-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_reportenegativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='Diego Andrés Viloria Carpintero', max_length=255)),
                ('nit', models.CharField(default='1.005.512.876-1', max_length=50)),
                ('tipo_documento', models.CharField(default='Cédula de Ciudadanía', max_length=50)),
                ('representante_legal', models.CharField(default='Diego Andrés Viloria Carpintero', max_length=255)),
                ('ciudad', models.CharField(default='Barranquilla', max_length=200)),
                ('departamento', models.CharField(default='Atlántico', max_length=200)),
                ('direccion', models.CharField(default='Calle 117 #42 - 56, Barranquilla (Atlántico)', max_length=255)),
                ('telefono', models.CharField(default='3146159776', max_length=50)),
                ('email', models.EmailField(default='Viloria542@gmail.com', max_length=254)),
                ('banco', models.CharField(blank=True, default='', max_length=200)),
                ('tipo_cuenta', models.CharField(blank=True, default='', max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='empresa/')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresa',
            },
        ),
    ]
