# Generated by Django 5.1.2 on 2026-06-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_perfilempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportenegativo',
            name='gestion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GESTIONADO', 'Gestionado'), ('ACUERDO', 'Acuerdo de pago'), ('ELIMINADO', 'Eliminado')], default='PENDIENTE', max_length=50),
        ),
    ]
