# Generated by Django 5.1.2 on 2026-08-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_alter_reportenegativo_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canal_origen',
            field=models.CharField(blank=True, choices=[('REFERIDO', 'Referido'), ('REDES_SOCIALES', 'Redes Sociales'), ('WEB', 'Sitio Web'), ('LLAMADA', 'Llamada / Telefónico'), ('PUBLICIDAD', 'Publicidad'), ('CAMPAÑA', 'Campaña'), ('OTRO', 'Otro')], default='', help_text='Origen del cliente (solo informativo en la ficha).', max_length=30, verbose_name='Canal de origen'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_contrato',
            field=models.DateField(blank=True, help_text='Obligatoria cuando el estado es CONTRATO_FIRMADO.', null=True, verbose_name='Fecha de firma del contrato'),
        ),
        migrations.AddField(
            model_name='recaudo',
            name='es_anticipo',
            field=models.BooleanField(default=False, help_text='Marcar si este recaudo corresponde a una cuota del anticipo pactado.', verbose_name='Abono a anticipo'),
        ),
        migrations.AddField(
            model_name='reportenegativo',
            name='obligation_status',
            field=models.CharField(choices=[('MORA', 'En mora'), ('DUDOSO_RECAUDO', 'Dudoso recaudo'), ('CARTERA_CASTIGADA', 'Cartera castigada'), ('SALDADO', 'Saldado'), ('INACTIVA', 'Inactiva'), ('CAN_MAL_MANEJO', 'Cancelada por mal manejo'), ('PAGO_VOL', 'Pago voluntario'), ('PAGO_VOL_MX', 'Pago voluntario (máximo)'), ('PAGO_JUR', 'Pago jurídico'), ('LIQ_PAT', 'Liquidación patrimonial'), ('CAN_PRESCR', 'Cancelada por prescripción'), ('CAN_VOL', 'Cancelada voluntariamente'), ('CAN_VOL_MM', 'Cancelada voluntariamen. (mal manejo)'), ('T_EXTRAVIADA', 'Tarjeta extraviada'), ('NO_ENTREG', 'No entregada'), ('TARJETA_NO_RENOVADA', 'Tarjeta no renovada'), ('T_ROBADA', 'Tarjeta robada'), ('REESTRUCTURADA', 'Reestructurada'), ('REFINANCIADA', 'Refinanciada'), ('TRANSF_PRODUCTO', 'Transferencia de producto'), ('NORMAL', 'Normal'), ('COMPRADA', 'Comprada'), ('CANCELADA', 'Cancelada'), ('OTRO', 'Otro')], default='OTRO', max_length=30, verbose_name='Estado de la obligación'),
        ),
        migrations.AlterField(
            model_name='reportenegativo',
            name='gestion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GESTIONADO', 'Gestionado'), ('ACUERDO', 'Acuerdo de pago'), ('ELIMINADO', 'Eliminado'), ('ELIMINADO_EXITO', 'Eliminado con éxito'), ('INVIABLE', 'Inviable'), ('SALDADO', 'Saldado')], default='PENDIENTE', max_length=50),
        ),
    ]
