# Generated by Django 5.1.2 on 2026-08-11 06:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_cliente_canal_origen_cliente_fecha_contrato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha de la novedad')),
                ('descripcion', models.TextField(verbose_name='Novedad / observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_manuales', to='comercial.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_manuales_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad manual',
                'verbose_name_plural': 'Actividades manuales',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
