# Generated by Django 5.1.2 on 2026-06-09 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('CIVIL', 'Civil'), ('PENAL', 'Penal'), ('LABORAL', 'Laboral'), ('ADMINISTRATIVO', 'Administrativo'), ('FAMILIA', 'Familia'), ('COMERCIAL', 'Comercial'), ('OTRO', 'Otro')], default='CIVIL', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20)),
                ('juzgado', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='comercial.cliente')),
                ('colaborador', models.ForeignKey(blank=True, limit_choices_to={'role': 'COLABORADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Actuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuaciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuaciones', to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Actuación',
                'verbose_name_plural': 'Actuaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
