# Generated by Django 5.1.2 on 2026-06-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='proceso',
            name='cantidad_reportes',
            field=models.IntegerField(default=0, verbose_name='Cantidad reportes a gestionar'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='ciudad_juzgado_competente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proceso',
            name='clave_datacredito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proceso',
            name='clave_transunion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proceso',
            name='cuotas_anticipo',
            field=models.IntegerField(default=1, verbose_name='Dividir anticipo en X cuotas'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='departamento_competente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proceso',
            name='estado_comercial',
            field=models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('CONTACTADO', 'Contactado'), ('PETICION_RADICADA', 'Petición Radicada'), ('EN_TRAMITE', 'En Trámite'), ('CONTRATO_FIRMADO', 'Contrato Firmado'), ('FINALIZADO', 'Finalizado'), ('PERDIDO', 'Perdido')], default='PROSPECTO', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='estado_legal',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='proceso',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='porcentaje_anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Anticipo inicial'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='referidor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referidor / Canal de origen'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='proceso',
            name='score_datacredito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='score_transunion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='tipo_servicio',
            field=models.CharField(choices=[('ELIMINACION_REPORTES', 'Eliminación de Reportes'), ('TUTELA', 'Tutela'), ('SIC', 'SIC'), ('CARTERA', 'Cartera'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
        migrations.AddField(
            model_name='proceso',
            name='valor_expectativa_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='proceso',
            name='valor_pactado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nombre / Título del proceso'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='radicado',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
