# Generated by Django 5.1.2 on 2026-06-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_cliente_tipo_cliente_barrio_and_more'),
        ('procesos', '0002_remove_proceso_ciudad_remove_proceso_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='estado_comercial',
            field=models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('CONTACTADO', 'Contactado'), ('CONTRATO_FIRMADO', 'Contrato Firmado'), ('PETICION_RADICADA', 'Petición Radicada'), ('EN_TRAMITE', 'En Trámite'), ('FINALIZADO', 'Finalizado'), ('PERDIDO', 'Perdido')], default='PROSPECTO', max_length=50),
        ),
        migrations.CreateModel(
            name='CasoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('TUTELA', 'Acción de Tutela'), ('SIC', 'SIC'), ('CARTERA', 'Cartera'), ('ELIMINACION_REPORTES', 'Eliminación de Reportes'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('radicado_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('demandante_accionante', models.CharField(blank=True, default='', max_length=255)),
                ('demandado_accionado', models.CharField(blank=True, default='', max_length=255)),
                ('juzgado_entidad', models.CharField(blank=True, default='', max_length=255)),
                ('etapa_actual', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('proximo_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion_caso', models.TextField(blank=True, default='')),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('url_sharepoint', models.URLField(blank=True, null=True)),
                ('contrato_autenticado_recibido', models.BooleanField(default=False)),
                ('habilitado_modulo_juridico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('abogado_asignado', models.ForeignKey(blank=True, limit_choices_to={'role': 'ABOGADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_juridicos', to='comercial.cliente')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_juridicos', to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Caso Jurídico',
                'verbose_name_plural': 'Casos Jurídicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
