# Generated by Django 5.1.2 on 2026-06-10 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_alter_proceso_estado_comercial_casojuridico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TUTELA', 'Acción de Tutela'), ('DERECHO_PETICION', 'Derecho de Petición'), ('DEMANDA', 'Demanda'), ('RECURSO', 'Recurso'), ('CONCILIACION', 'Conciliación'), ('PRUEBA', 'Práctica de Prueba'), ('NOTIFICACION', 'Notificación'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto'), ('ARCHIVADO', 'Archivado'), ('APELACION', 'En Apelación')], default='ACTIVO', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('resultado', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('abogado', models.ForeignKey(blank=True, limit_choices_to={'role': 'ABOGADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_internos', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_internos', to='procesos.casojuridico')),
            ],
            options={
                'verbose_name': 'Proceso Interno',
                'verbose_name_plural': 'Procesos Internos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
