# Generated by Django 5.1.2 on 2026-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_servicio_alter_proceso_tipo_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado Proceso',
                'verbose_name_plural': 'Estados Proceso',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado_comercial',
            field=models.CharField(default='NUEVO', max_length=100),
        ),
    ]
