# Generated by Django 5.1.2 on 2026-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_estadoproceso_alter_proceso_estado_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=300)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('complejidad', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA_BAJA', 'Media-Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('MUY_ALTA', 'Muy Alta')], default='', max_length=20)),
                ('emails', models.TextField(blank=True, help_text='Uno por linea')),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['razon_social'],
            },
        ),
    ]
