# Generated by Django 5.1.2 on 2026-06-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesointerno',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='procesointerno',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
