# Generated by Django 5.1.2 on 2026-06-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0009_procesointerno_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesointerno',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor facturable de este proceso interno', max_digits=14, null=True),
        ),
    ]
