# Generated by Django 5.1.2 on 2026-07-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0010_procesointerno_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos', to='procesos.servicio'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Nombre / Título del proceso'),
        ),
    ]
