# Generated by Django 5.1.2 on 2026-08-11 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0013_documento_file_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='archivo',
            field=models.FileField(blank=True, help_text='Doc, PDF, imagen u otro archivo asociado a la entidad.', null=True, upload_to='entidades/', verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='fecha_contrato',
            field=models.DateField(blank=True, help_text='Obligatoria cuando el estado comercial es CONTRATO_FIRMADO.', null=True, verbose_name='Fecha de firma del contrato'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='valor_expectativa_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Expectativa total (COP)'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='valor_pactado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor pactado (= expectativa)'),
        ),
        migrations.CreateModel(
            name='AnticipoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='N° de cuota')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor de la cuota')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipo_cuotas', to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Cuota de anticipo',
                'verbose_name_plural': 'Cuotas de anticipo',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=100)),
                ('estado_nuevo', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='procesos.proceso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de estado',
                'verbose_name_plural': 'Cambios de estado',
                'ordering': ['-fecha'],
            },
        ),
    ]
