# Generated by Django 5.1.2 on 2026-08-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_cliente_canal_origen_cliente_fecha_contrato_and_more'),
        ('procesos', '0014_entidad_archivo_proceso_fecha_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='comercial.cliente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='procesos.proceso'),
        ),
    ]
